package com.apnablog.blog.repository;

import com.apnablog.blog.utils.factory.BlogFactory;
//import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;

//@Component
public class DbInit {
    private final BlogUserRepository userRepository;

    public DbInit(BlogUserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @PostConstruct
    public void init() {
        // Save blog users generated by the factory class and generate and save a blog admin
        BlogFactory.BLOG_USERS.forEach(userRepository::save);
        userRepository.save(BlogFactory.generateBlogAdmin());
    }
}
